name: build

on:
  push:
    branches:
      - main

  pull_request:

  merge_group:

  schedule:
    - cron: '0 1 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  HUSKY: 0

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: ⚙️ Setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          standalone: true

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: .node-version
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm prettier

  build:
    needs:
      - lint
    runs-on: ${{ matrix.arch.os }}
    name: build (${{ matrix.distro }}, ${{ matrix.arch.name }})

    strategy:
      fail-fast: false
      matrix:
        distro:
          - focal
          - jammy
        arch:
          - name: x86_64
            os: ubuntu-24.04
          - name: aarch64
            os: ubuntu-24.04-arm

    env:
      DISTRO: ${{ matrix.distro }} # build target, name required by binary-builder
      ARCH: ${{ matrix.arch.name }} # build target, name required by binary-builder

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: binary-builder
        uses: containerbase/internal-tools@3be574538ca7e104ae19a98c5f71ac8e314b4379 # v3.5.24
        with:
          command: binary-builder
          dry-run: ${{github.ref != 'refs/heads/main'}}
          token: ${{ secrets.GITHUB_TOKEN }}

  # Catch-all required check for matrix
  success:
    needs:
      - lint
      - build
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: always()
    steps:
      - name: Fail for failed or cancelled build tests
        if: |
          needs.build.result == 'failure' ||
          needs.build.result == 'cancelled'
        run: exit 1
      - name: Fail for failed or cancelled lint
        if: |
          needs.lint.result == 'failure' ||
          needs.lint.result == 'cancelled'
        run: exit 1
